### ISSUE TITLE
Component never removed causing memory leak

### ISSUE THREAD

**Issue by ryanjohn1** [grandstaish/compartment#5]
I'm seeing an issue where a component is never removed from the components Map in ComponentCacheApplication under certain circumstances.
Usually this is removed in the onDestroy method of a fragment when the fragment is destroyed.
However, if you're on an activity with a fragment, then background the app, the fragment isn't destroyed at that point so the component is still in the map. If I then follow a push notification link directly into that same screen again then it is recreated and the component is recreated and added to the map. The last one was never removed which leaks the original activity.

This is happening a lot as we have a chat screen which frequently gets backgrounded and then reopened through a push notification when the user gets a new message.

Any ideas on how best to handle this situation?

**Comment by ryanjohn1** [comment]
This is with v0.0.3
I've just noticed the changes you made in v0.0.4; deprecating ComponentCacheApplication. This might fix the problem. I'll upgrade, change to using ComponentCacheActivity and check whether the issue is resolved

**Comment by ryanjohn1** [comment]
This issue is resolved by v0.0.4
Great work!

**Comment by grandstaish** [comment]
Great news :+1:
